added nav bar and added cchdo to gleaner.yaml
nein09/polder-federated-search pull request #42
Opened 2022-05-23 23:26 UTC by yemoski

Navigation Bar added
 Added CCHDO to gleaner.yaml

2022-05-27 21:29 UTC, nein09 requested changes
A few changes to request, and a question - what's the `polar-federated-search` submodule?

I tried out the CCHDO indexing and it did complete, BUT CCHDO data isn't coming up in full-text queries, so there might be some SPARQL changes that need to happen. Let's look at that together on Monday.

Thank you!

2022-05-27 21:29 UTC, nein09 commented on app/static/css/_form.scss
> +    width:00px;
I think the background on this might work better as `$soft-white` -can you give that a try please?

2022-05-27 21:35 UTC, nein09 commented
> A few changes to request, and a question - what's the `polar-federated-search` submodule?
> 
> I tried out the CCHDO indexing and it did complete, BUT CCHDO data isn't coming up in full-text queries, so there might be some SPARQL changes that need to happen. Let's look at that together on Monday.
> 
> Thank you!

(Those SPARQL changes can happen separately from this pull request)

2022-05-27 23:25 UTC, yemoski commented on app/static/css/_form.scss
> +@keyframes load {
Oh yeah, that was a sub module I had, I can delete that it is not needed.

I can delete the ellipse since we do not need the animiation

2022-05-27 23:49 UTC, yemoski commented
Hi, 
Thanks for all the comments.
I just finished implementing all the changes.
Should I make a new pull request with the changes?

2022-05-27 23:50 UTC, nein09 commented
@yemoski If you push them up to this branch, they should automatically show up in this pull request here.

2022-05-27 23:57 UTC, yemoski commented
sounds good!

2022-05-30 16:55 UTC, nein09 commented on app/templates/about.html
> +        <div clas="covered_repositories">
Whoa, looks like your 'about' changes crept in here, too! It'd be better to keep these on another branch so we can look at one thing at a time.

2022-05-30 16:59 UTC, nein09 commented on app/templates/about.html
> +        <div clas="covered_repositories">
I'll take a look at them now that they're in here, though, since there are a couple other changes that need to happen before I merge this anyway.

2022-05-30 16:59 UTC, nein09 commented
The submodule is still in here, and `main-nav` still needs to be a `nav` before this goes in- thank you.

2022-05-30 22:50 UTC, merged